#ifndef __FUNC_ENUMS_HPP__
#define __FUNC_ENUMS_HPP__

#define DINAMIK_MEMORY


enum COMP_POSITION{
    SOL,
    SAG,
    UST,
    ALT,
    ORTA,
    GENISLEYEN_SATIR,
    GENISLEYEN_SATIRSUTUN,
};


//menusf//
enum MENUS_FUNC{
    MENUSF_TANIMSIZ_BIR = 1,
    MENUSF_TANIMSIZ_IKI = 2,
    MENUSF_TANIMSIZ_UC = 3,

    MENUSF_GITHUB,
    MENUSF_ISSUES_PROBLEM_REPORT
};

//buttonsf//
enum BUTTONS_FUNC{
    BUTTONSF_TANIMSIZ_BIR = 1,
    BUTTONSF_TANIMSIZ_IKI = 2,
    BUTTONSF_TANIMSIZ_UC = 3,

    BUTTONSF_LOGIN_BILGILERI_GONDER,
    BUTTONSF_MAIN_RUN_COMMAND
};

//textctrlsf
enum TEXTCTRLS_FUNC{
    TEXTCTRLSF_TANIMSIZ_BIR = 1,
    TEXTCTRLSF_TANIMSIZ_IKI,
    TEXTCTRLSF_TANIMSIZ_UC,

    TEXTCTRLSF_LOGIN_SERVER_HOST_IP,
    TEXTCTRLSF_LOGIN_SERVER_HOST_PORT,
    TEXTCTRLSF_LOGIN_SERVER_RCON_PASSWORD,
    TEXTCTRLSF_LOGIN_SERVER_RCON_PORT
    
};

//configParser CONFIG_SETTINGS//
enum CONFIG_SETTINGS{
    CONFIG_SETTINGS_SERVER_IP = 1,
    CONFIG_SETTINGS_SERVER_PORT,
    CONFIG_SETTINGS_RCON_SERVER_PORT,
    CONFIG_SETTINGS_RCON_PASSWORD
};

//lockWindow//
enum LOCK_WINDOW_PARAMS{
    LWP_LOCKED,
    LWP_LOCK_MAX100,
    LWP_LOCK_MIN100,
    LWP_LOCK_MIN_MAX100
};



#endif 